//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppSQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiPhuTrach
    {
        public int MaNguoiPhuTrach { get; set; }
        public string TenNguoiPhuTrach { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public int MaDV { get; set; }
        public string SDT { get; set; }
    
        public virtual DonVi DonVi { get; set; }
    }
}
