//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppSQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuaChua
    {
        public int MaLSC { get; set; }
        public System.DateTime thoigian { get; set; }
        public int MaTB { get; set; }
        public int MaPL { get; set; }
        public int MaSC { get; set; }
        public string ChatLuong { get; set; }
        public string TinhTrang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LoaiSuaChua LoaiSuaChua { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
