//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppSQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBi()
        {
            this.PhanLoais = new HashSet<PhanLoai>();
            this.SuaChuas = new HashSet<SuaChua>();
            this.ThuHois = new HashSet<ThuHoi>();
        }
    
        public int MaTB { get; set; }
        public string TenThietBi { get; set; }
        public int MaNCC { get; set; }
        public int MaNhom { get; set; }
        public int MaDV { get; set; }
        public string SoLuong { get; set; }
        public int MaLK { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual LinhKien LinhKien { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhomThietBi NhomThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanLoai> PhanLoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuaChua> SuaChuas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuHoi> ThuHois { get; set; }
    }
}
