//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppSQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuHoi
    {
        public int MaLTH { get; set; }
        public int MaTB { get; set; }
        public int MaPL { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime Thoigian { get; set; }
        public int MaTH { get; set; }
    
        public virtual LoaiThuHoi LoaiThuHoi { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
